---
- hosts: all
  become: yes
  become_user: root
  vars:
    container_image: flask_image
    container_name: flask_app

  tasks:
    - name: Clone from github
      git:
        repo: 'https://github.com/mdashaikh/devops-coding-challenge.git'
        dest: /webapps/devops

    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools', 'python-docker']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: Update apt and install docker.io
      apt: update_cache=yes name=docker.io state=latest

    - name: Build Docker image
      docker_image:
        name: "{{ container_image }}"
        build:
          path: /vagrant
          args:
            log_volume: /var/log/flask_app
        source: build

    - name: Create default containers
      command: docker run --restart always -d --name "{{ container_name }}" -p 80:5000 "{{ container_image }}" --log-opt max-size=10m --log-opt max-file=5
    - name: Get listen ip address
      debug:
        var: ansible_enp0s8.ipv4.address
