---
- hosts: all
  become: true
  vars:
    container_image: flask_image
    container_name: flask_app

  tasks:
    - name: Clone from github
      git:
        repo: 'https://bitbucket.org/azneita/devops-challenge.git'
        dest: /home/webapps/devops

    - name: Copy form /vagrant to /home
      copy:
        src: /vagrant/Dockerfile
        dest: /home

    - name: Change app.py file
      shell: |
        sed -i 's/from werkzeug.contrib.fixers import ProxyFix/#from werkzeug.contrib.fixers import ProxyFix/g' /home/webapps/devops/app.py
        sed -i 's/app.wsgi_app = ProxyFix(app.wsgi_app)/#app.wsgi_app = ProxyFix(app.wsgi_app)/g' /home/webapps/devops/app.py

    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools', 'python-docker']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: Update apt and install docker.io
      apt: update_cache=yes name=docker.io state=latest

    - name: Build Docker image
      docker_image:
        name: "{{ container_image }}"
        build:
          path: /home
          args:
            log_volume: /var/log/flask_app
        source: build

    - name: Create default containers
      command: docker run --restart always -d --name "{{ container_name }}" -p 80:5000 "{{ container_image }}" --log-opt max-size=10m --log-opt max-file=5
    - name: Get listen ip address
      debug:
        var: ansible_enp0s8.ipv4.address
